# -*- coding: utf-8 -*-
"""pysql_3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1l-XPi_cpgQ8JFPKD1lRV8aN_C3OPjuIZ
"""

from sqlalchemy import create_engine, Column, Integer, String
from sqlalchemy.orm import declarative_base, sessionmaker

engine = create_engine('sqlite:///meu_banco.db', echo=True)
Base = declarative_base()

# Mapeamento da tabela para classe Python
class Usuario(Base):
    __tablename__ = 'jogadores'
    id = Column(Integer, primary_key=True, autoincrement=True)
    nome = Column(String)
    matricula = Column(String, unique=True)
    curso = Column(String)
    contato = Column(String, unique=True)

# Criação da tabela no banco
Base.metadata.create_all(engine)

# Criação da sessão para interagir
Session = sessionmaker(bind=engine)
session = Session()

def add_n_commit(nome, matricula, curso, contato):
    novo_usuario = Usuario(nome=nome, matricula=matricula, curso=curso, contato=contato)
    session.add(novo_usuario)
    session.commit()



add_n_commit("Ana", "261001203", "Medicina", "61981231213")
add_n_commit("Joao", "261001300", "Medicina", "61981231213")

usuarios = session.query(Usuario).all()

print("Usuários no banco de dados:")
for usuario in usuarios:
    print(f"ID: {usuario.id}, Nome: {usuario.nome}, Curso: {usuario.curso}, Contato: {usuario.contato}")